# Generated by Django 3.0.3 on 2021-10-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211022_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
